### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/layer_styles.csv' 

### ISSUE THREAD

**Issue by mussels** [jkall/qgis-fit-plugin#3]
I get the following error after filling in the first to fields (required) on the 'FIT file importer', the first pointing to the wahoo elemnt exports folder and the second one a folder within my ubuntu documents, then click OK:

newlayerstylesfile = open(os.path.join(os.path.dirname(tempfile.gettempdir()),"layer_styles.csv"), "w+")
PermissionError: [Errno 13] Permission denied: '/layer_styles.csv'
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] 
QGIS version: 3.26.2-Buenos Aires Buenos Aires, feec3d3b12

**Comment by jkall** [comment]
Strange. The expected path on Ubuntu would be /tmp/layer_styles.csv

Try this in the shell: 
```
$python
>>> import tempfile
    >>>tempfile.gettempdir()
```

What path do you get?

**Comment by mussels** [comment]
I get '/tmp' from the QGIS Python console and the same from terminal:

$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> tempfile.gettempdir()
'/tmp'

..which is what you expect but I still get the same error:
PermissionError: [Errno 13] Permission denied: '/layer_styles.csv'

**Comment by jkall** [comment]
fixed by @rhssk in https://github.com/jkall/qgis-fit-plugin/commit/9319e3ceb6401f6fa87161f130bd119169bec343
