### ISSUE TITLE
FIT file importer cannot see .fit in lower case

### ISSUE THREAD

**Issue by mussels** [jkall/qgis-fit-plugin#4]
On the wahoo elemnt, FIT files are named with a lower case file extension, the file importer expect upper case *.FIT and cannot see the files.
Workaround: renaming the FIT file with an upper case extension allow the FIT file importer to see the files.

**Comment by jkall** [comment]
fixed in https://github.com/jkall/qgis-fit-plugin/commit/7b58f54cac4b767fe24e4608e6e9a2e28d052a80
